# Generated by Django 4.2.23 on 2025-07-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='管理员')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号码')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('img', models.FileField(upload_to='city/', verbose_name='图片')),
                ('category', models.CharField(max_length=50, verbose_name='商品分类')),
                ('description', models.TextField(verbose_name='商品描述')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='兼职人员')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('time', models.SmallIntegerField(choices=[(1, '空闲'), (2, '配送中')], default=1, verbose_name='状态')),
                ('workload', models.CharField(default='0', max_length=100, verbose_name='工作量')),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.CharField(error_messages={'unique': '该学号已存在，请使用其他学号。'}, max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号码')),
                ('qsld', models.CharField(max_length=32, verbose_name='寝室号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('datetime', models.CharField(max_length=32, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('goodsDetails', models.CharField(max_length=100, verbose_name='商品信息')),
                ('money', models.CharField(max_length=100, verbose_name='费用')),
                ('status', models.SmallIntegerField(choices=[(1, '未发货'), (2, '配送中'), (3, '已送达')], default=1, verbose_name='配送状态')),
                ('createTime', models.CharField(max_length=100, verbose_name='创建时间')),
                ('sendTime', models.CharField(blank=True, max_length=100, null=True, verbose_name='配送时间')),
                ('completeTime', models.CharField(blank=True, max_length=100, null=True, verbose_name='完成时间')),
                ('is_paid', models.BooleanField(default=False, verbose_name='支付状态')),
                ('deliverId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app01.job')),
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app01.stu')),
            ],
        ),
    ]
